let userName = prompt("Adınızı giriniz")
myName = document.querySelector("span#myName")
myName.innerHTML = userName
let myClock = document.querySelector("#myClock")
const now = new Date()
let minutes = now.getMinutes()
let hours = now.getHours()
let seconds = now.getSeconds()
let gunler = ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"];
let bugun = new Date().getDay() -1 
let gunAdi = gunler[bugun]
myClock.innerHTML = `Saat: ${hours}:${minutes}:${seconds} Gün: ${gunAdi}`
